workspace = "boringcache/benchmarks"

[adapters.docker]
tag = "docker-cache-proof-blockscout-frontend"
no-platform = true
no-git = true
fail-on-cache-error = true
metadata-hints = ["benchmark=docker-cache-proof", "case=blockscout-frontend", "source-ref=rolling3"]
command = [
  "docker",
  "buildx",
  "build",
  "--file",
  "../../../../.work/blockscout-frontend/source/Dockerfile",
  "--platform",
  "linux/amd64",
  "--build-arg",
  "GIT_COMMIT_SHA=3e8f4939ab7b33311d5ebc591bad03ec1bcb597c",
  "--build-arg",
  "GIT_TAG=",
  "--push",
  "--tag",
  "ghcr.io/boringcache/blockscout-frontend-proof:rolling3",
  "../../../../.work/blockscout-frontend/source/.",
]
