bazel = ["grpc"]
buck2 = ["buck2-prelude", "executorch"]
cargo = ["deno", "zed"]
ccache = ["obs-studio"]
docker = ["chroma", "discourse", "duckgres", "hugo", "immich", "linkerd2", "llama-cpp", "mastodon", "n8n", "posthog", "qdrant"]
go = ["hugo"]
gradle = ["opentelemetry-java"]
maven = ["spring-ai"]
moon = ["gogs", "opencut", "zitadel"]
nix = ["helix"]
pants = ["pants-jvm", "stackstorm"]
sbt = ["msgpack-java"]
turbo = ["n8n"]
xcode = ["obs-studio"]
