bazel = ["grpc"]
buck2 = ["executorch"]
cargo = ["deno", "zed", "zed-bundle"]
ccache = ["obs-studio"]
docker = ["chroma", "discourse", "duckgres", "hugo", "immich", "linkerd2", "llama-cpp", "mastodon", "n8n", "posthog", "qdrant"]
go = ["hugo"]
gradle = ["opentelemetry-java"]
maven = ["spring-ai"]
moon = ["zitadel"]
nix = ["helix", "zed"]
nx = ["storybook"]
pants = ["backend-ai"]
sbt = ["lila", "play"]
turbo = ["n8n"]
xcode = ["obs-studio"]
