github = "ubuntu-latest"
github-arm = "ubuntu-24.04-arm"
macos = "macos-26"
depot-4 = "depot-ubuntu-24.04-4"
depot-8 = "depot-ubuntu-24.04-8"
namespace-4 = "namespace-profile-buildkit-4c"
namespace-8 = "namespace-profile-buildkit-8c"
local = "local"
