workspace = "boringcache/benchmarks"

[adapters.nix]
tag = "zed-nix"
no-platform = true
no-git = true
command = ["nix", "build", "github:zed-industries/zed/a6169ca96987105be7d60a5051f3155eb6225ccc#default", "-L", "--no-update-lock-file", "--option", "accept-flake-config", "false"]
