repo = "immich-app/immich"
branch = "main"
start_sha = "a3c8b359f2fdc47699f1530215a23fe8bd34c454"
check = "docker image inspect immich-server-benchmark:local"

[runs]
boringcache-docker = ["github", "github-arm", "local"]
boringcache-docker-plus = ["github", "github-arm", "local"]
gha = ["github", "github-arm"]
ghcr = ["github", "github-arm"]
