repo = "mastodon/mastodon"
branch = "main"
start_sha = "9b97c67be3c67e992c184167bd7425502aad12da"
check = "docker image inspect mastodon-server-benchmark:local"

[runs]
boringcache-docker = ["github", "local"]
boringcache-docker-plus = ["github", "local"]
gha = ["github"]
ghcr = ["github"]
