provider = "depot"
level = "base"
machine = "depot builder"
runners = ["github"]
secrets = ["DEPOT_TOKEN", "DEPOT_DOCKER_PROJECT_ID"]
setup = ["depot"]
program = ["depot"]
replaces = ["docker", "buildx"]
args = ["--project", "${DEPOT_DOCKER_PROJECT_ID}"]

[cold]
prepare = ["depot cache reset --project \"$DEPOT_DOCKER_PROJECT_ID\""]
