provider = "github-actions-cache"
level = "base"
actions_only = true
runners = ["github", "github-arm"]
setup = ["buildx"]
args = ["--cache-from", "type=gha,scope=${BENCH_SCOPE}", "--cache-to", "type=gha,scope=${BENCH_SCOPE},mode=max"]

[warm]
args = ["--cache-from", "type=gha,scope=${BENCH_SCOPE}"]
