provider = "github-container-registry"
level = "base"
actions_only = true
runners = ["github", "github-arm"]
setup = ["buildx", "ghcr"]
args = ["--set=*.cache-from=type=registry,ref=ghcr.io/${GITHUB_REPOSITORY}-cache:${BENCH_SCOPE}", "--set=*.cache-to=type=registry,ref=ghcr.io/${GITHUB_REPOSITORY}-cache:${BENCH_SCOPE},mode=max"]

[warm]
args = ["--set=*.cache-from=type=registry,ref=ghcr.io/${GITHUB_REPOSITORY}-cache:${BENCH_SCOPE}"]
