workspace = "boringcache/benchmarks"

[adapters.bazel]
fail-on-cache-error = true
tag = "grpc-bazel"
no-platform = true
no-git = true
metadata-hints = ["benchmark=grpc", "workload=csm-client-server"]
command = [
  "./tools/bazel",
  "--bazelrc=../bench.bazelrc",
  "build",
  "--config=opt",
  "--remote_download_outputs=toplevel",
  "--remote_cache_async=false",
  "--remote_max_connections=64",
  "--remote_timeout=10m",
  "--incompatible_strict_action_env",
  "--action_env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "--host_action_env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "--repo_env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "--repo_env=CC=/usr/bin/gcc",
  "--repo_env=CXX=/usr/bin/g++",
  "--repo_env=LD=/usr/bin/ld",
  "//examples/cpp/csm:csm_greeter_client",
  "//examples/cpp/csm:csm_greeter_server",
]
