workspace = "boringcache/benchmarks"

[adapters.bazel]
fail-on-cache-error = true
tag = "grpc-bazel"
no-platform = true
no-git = true
metadata-hints = ["benchmark=grpc", "workload=csm-client-server"]
command = [
  "./tools/bazel",
  "--bazelrc=../bench.bazelrc",
  "build",
  "--config=opt",
  "//examples/cpp/csm:csm_greeter_client",
  "//examples/cpp/csm:csm_greeter_server",
]
