workspace = "boringcache/benchmarks"

[adapters.nix]
tag = "helix-nix"
no-platform = true
no-git = true
command = ["nix", "build", "github:helix-editor/helix/ba40e547426b0f9896c8bdc699a4ab11f2b37dbc#default", "-L", "--no-update-lock-file", "--option", "accept-flake-config", "false"]
