workspace = "boringcache/benchmarks"

[adapters.docker]
tag = "docker-cache-proof-blockscout-frontend"
no-platform = true
no-git = true
fail-on-cache-error = true
metadata-hints = ["benchmark=docker-cache-proof", "case=blockscout-frontend", "source-ref=rolling4"]
command = [
  "docker",
  "buildx",
  "build",
  "--file",
  "../../../../.work/blockscout-frontend/source/Dockerfile",
  "--platform",
  "linux/amd64",
  "--build-arg",
  "GIT_COMMIT_SHA=39bb7b3e6e5d4b077cfd08f26a5e40e82e21b52a",
  "--build-arg",
  "GIT_TAG=",
  "--push",
  "--tag",
  "ghcr.io/boringcache/blockscout-frontend-proof:rolling4",
  "../../../../.work/blockscout-frontend/source/.",
]
