repo = "gohugoio/hugo"
branch = "master"
start_sha = "ec69d0e64931715e490ae411cba2b305636d20e0"
check = "docker image inspect hugo-benchmark:local"

[runs]
boringcache-docker = ["github", "github-arm", "local"]
boringcache-docker-plus = ["github", "github-arm", "local"]
gha-plus = ["github", "github-arm"]
gha = ["github", "github-arm"]
ghcr = ["github", "github-arm"]
